dalek-cryptography/curve25519-dalek

Cargo.toml
src/lib.rs
src/scalar.rs

This adds a dependency on the `rand` crate, used to construct an
OS-backed CSPRNG.  The implementation in this commit is somewhat
inefficient as it constructs a new OsRng object every time; it might be
better to construct it once.  (Seems like a lot of overhead for a few
getrandom(2) calls...)

Add a Scalar::random() constructor

---

src/curve.rs
src/field.rs
src/scalar.rs
src/util.rs

These commits move the `CTAssignable` trait into the `util` module, and provide implementations of the type for `Scalar`s and `FieldElement`s.

Move CTAssignable trait and implement it for more types

---

Cargo.toml
src/curve.rs
src/field.rs
src/lib.rs
src/scalar.rs

This crate does not depend on std. I would like to use it in a #![no_std] Rust program, but to do that this library can't link against std.

Add #![no_std] (fixes #16)

---

src/curve.rs
src/field.rs
src/util.rs

The name `CTNegateable` is kind of awkward, but I think gets the point across, and it's in any case only used when importing the trait.

Add a conditional negation trait with generic implementation

---

Cargo.toml

These will get picked up the next time you publish the crate (provided you have a recent version of cargo):
https://crates.io/categories/cryptography

Add "cryptography" and "no-std" categories

---

Cargo.toml
src/constants.rs
src/curve.rs
src/decaf.rs
src/field.rs
src/lib.rs

This branch has a very WIP, first-draft implementation of Decaf for Curve25519.  It's probably full of errors, so it's feature-gated with the `yolocrypto` flag.
Merging it now instead of later means:
* It's easy to keep it in sync with changes to the rest of the tree;
* We can start thinking about how to use its API in other protocols, even if the implementation is incomplete.

First draft of Decaf support

---

Cargo.toml
src/lib.rs
src/scalar.rs

Add a generic hash-to-scalar function, parameterized by a `Digest` instance with 512 bits of output.

Hash to scalar

---

.travis.yml
Cargo.toml
src/curve.rs
src/decaf.rs
src/field.rs
src/lib.rs
src/scalar.rs

This allows us to build (and run tests) on the stable and beta channels. `cargo bench` still only runs on nightly, since it's feature gated. To run the benchmarks, one must:
1) use nightly
2) do: `cargo bench --features="yolocrypto bench"`
This fixes the issue mentioned in #38.
It also cleans up some of the benchmarks by moving them to separate modules. (This part might cause conflicts. If so, I'll take responsibility for the cleanup.)

Make benchmarks and #[feature(test)] dependent on feature bench

---

Cargo.toml
src/constants.rs
src/curve.rs
src/decaf.rs
src/lib.rs

This is feature-gated on nightly because I'm not feeling good about stack-allocating a 30K table.  Maybe it's not a big deal, in which case we can just throw away the `box`es.

Generic basepoint precomputations.

---

.travis.yml

Test nightly features on nightly channel.  I merged the previous one since I thought I had introduced an error while refactoring the `cfg` gating for `radix_51`, but I think it was instead an error in the Travis config.

2nd attempt at fixing Travis config

---

src/curve.rs
src/lib.rs

- Gate no_std on the "std" feature
- Import core when std is present
- Import collections when std is absent
- Add a placeholder gated "use" directive for Box in curve.rs

no_std import cleanups

---

src/curve.rs

Generalize `double_scalar_mult_vartime` to operate on `k` scalars and `k` points.

variable time k-fold scalarmult

---

.travis.yml
Cargo.toml
src/curve.rs
src/decaf.rs
src/lib.rs
src/scalar.rs

The serializable objects are `ExtendedPoint`s, `DecafPoint`s, and `Scalar`s.
Point decompression happens in the `Deserialize` implementation, causing a parse error on decompression.  Users can therefore derive `Serialize, Deserialize` on structs containing points; input data will either deserialize correctly to structs containing valid points, or not at all.
This code is currently not compatible with `serde_json`, because JSON doesn't have a native byte string type.  The `serde_json` backend seems to serialize a byte string as an array; deserialization fails because the parser sees an array, not a byte string, and `visit_bytes` is never called.  I'm not sure it's worthwhile to put in a workaround to allow support for a data format that doesn't have byte strings.

Add Serde support

---

src/curve.rs
src/decaf.rs

Uses Decaf-flavoured elligator (i.e., following the description in Appendix C of the Decaf paper).  That function is kept private until we do proper (bidirectional) elligator support.

Implement DecafPoint::{random, hash_from_bytes, from_hash}

---

src/decaf.rs

The implementation of Elligator-flavoured Decaf I wrote had an overflow bug, caused by a too-long sequence of additions of `FieldElements`.  This is a problem for the default 32-bit implementation, but not for the 64-bit `radix_51` implementation, which I was using when I wrote the code.
Because Rust traps overflows in debug builds, this bug was caught by the unit test.  However, it would be good to try to prevent the same mistake in the future.
I think it's possible to do this in a hacky way now, but it would be extremely ugly and coarse, creating a new type name for each interval.  
Const generics, as in [Rust RFC 2000](https://github.com/rust-lang/rfcs/pull/2000), would allow clean but coarse-grained (e.g., "number of bits of headroom) static analysis. I think waiting for this is the …

Fix overflow bug in Decaf Elligator code

---

.travis.yml
Cargo.toml
src/curve.rs
src/lib.rs

libcollections was recently merged into liballoc:
https://github.com/rust-lang/rust/pull/42648
This breaks curve25519-dalek when used with `no_std` on recent nightlies.
I went ahead and also added an "alloc" feature which no_std users can use to opt
into liballoc features (i.e. any code using Vec). This should have no effect on
anything but no_std usage. It does make it possible for people without
allocators to use curve25519-dalek if they want though. Might be nice for
"bare metal" development.
All that said, from what I can gather liballoc, while not "stable", should
likely stick around for the forseeable future.
Some backstory on the liballoc/libcollections merge here:
https://github.com/rust-lang/rust/pull/42565

Switch from libcollections to liballoc (gated on an "alloc" feature)

---

Cargo.toml

Previously, it was impossible to use an 0.6 version RustHash library with curve25519-dalek. The error when `from_hash` was called looked like `The trait digest::Digest is not implemented for sha2::Sha256`. After this change, code using version 0.6 compiles and runs correctly.

Update sha2 and digest deps

---

Cargo.toml

Otherwise subtle implicitly pulls in std because it's a default feature.
Tested and confirmed working in our `no_std` environment.

Only pull in subtle's std feature if "std" is enabled

---

src/curve.rs
src/decaf.rs
src/field.rs

This provides a constant-time version of the `k_fold_scalar_mult` function already in the `vartime` module.
Question: are we happy with the name? Does the `vartime::` submodule effectively separate two functions that do the same thing, but one is constant-time?

Add constant time k-fold scalar mult

---

Cargo.toml
src/curve.rs
src/decaf.rs
src/field.rs
src/field_32bit.rs
src/field_64bit.rs
src/scalar.rs

This should bring some decent (~30%) speedups wherever `slices_equal` is used, which for us is all over the place, but usually we are comparing relatively small slices (~32 bytes) so the speedup is not as drastic as it is for larger slice comparisons.

Bump subtle dependency to ^0.2 and use new API.

---

src/scalar.rs

Use the addition chain from
https://briansmith.org/ecc-inversion-addition-chains-01#curve25519_scalar_inversion.
In my benchmarking, this consistently runs at least 20% faster.

Use more efficient addition chain for scalar inversion.

---

src/field_32bit.rs
src/field_64bit.rs

Limbs are no longer accessible outside of the curve25519-dalek crate.
If you were relying on this behaviour, first you probably shouldn't be
doing that, second please contact us so we can determine the best way
forward for your use case.
This works for rustc>=1.18.0.

Make FieldElement limbs private to the curve25519-dalek crate.

---

src/constants_32bit.rs
src/constants_64bit.rs
src/lib.rs
src/scalar.rs
src/scalar_32bit.rs
src/scalar_64bit.rs

I (unfortunately) stomped on the scalar multiplication/squaring patches with this, so I apologize for that! 
These are 32/64 bit scalar implementations with add/sub/mul/square + montgomery reduction. Plain mul/square are done with two montgomery reductions since they aren't used very often and it makes the code much cleaner. 32 bit mul uses a karatsuba step, but it's hard to tell a difference either way with how little it's used.
Tests/documentation should be pretty decent. I tried to make the structure of the multiplications visible with the spacing, that makes it more obvious to me what is going on versus collapsing everything. Otherwise I tried to match the formatting in the rest of the project.

optimized scalar implementations for 32/64 bit

---

src/constants.rs
src/constants_32bit.rs
src/constants_64bit.rs
src/edwards.rs
src/lib.rs
src/montgomery.rs
src/ristretto.rs
src/scalar.rs

This depends on the Ristretto PR (#81), just because Ristretto uses different constants than Decaf.
This PR removes all unused constants from the `constants` module, renames them to have `DESCRIPTIVE_UPPER_CASE_NAMES`, and adds some missing docs.
It also makes nearly all of the numeric constants `pub(crate)`, so that we're not bound to providing them forever. (Most computations people would do with, e.g., the Edwards `d` value, should IMO be done in-crate).

Prune constants file

---

Makefile
src/backend/mod.rs
src/backend/u32/field.rs
src/backend/u32/mod.rs
src/backend/u64/constants.rs
src/backend/u64/field.rs
src/backend/u64/mod.rs
src/backend/u64/scalar.rs
src/constants.rs
src/curve_models/mod.rs
src/edwards.rs
src/field.rs
src/lib.rs
src/montgomery.rs
src/scalar.rs

This changeset converts more docs to use KaTeX.  Also there is a tweak to the `Scalar` API: `reduce_wide` is renamed to `from_bytes_mod_order_wide` to fit better with the other `Scalar` constructors.

Texify more formulas + Scalar API tweak

---

src/field.rs
src/ristretto.rs
vendor/ristretto.sage

This PR adds a new API to `FieldElement`s for doing batch inversion, and an implementation of the batchable double-and-encode operation for Ristretto. It does not include a write-up of the batchable Ristretto encoding, which will come in a later PR.
Both of these APIs are feature-gated on allocation.

Add batch inversion and batch Ristretto encoding

---

Cargo.toml

Document the weird build hack required for the precomputed tables, and keep all the dependencies together with a note that they can't fall out of sync.

Fix up Cargo.toml

---

src/constants.rs

I was playing around with using it for part of DAVROS and it should probably just exist anyway as a corollary to the other compressed basepoints.

Add compressed ristretto basepoint

---

src/backend/avx2/edwards.rs
src/edwards.rs
src/ristretto.rs

This allows iterators returning either &Scalars or Scalars, so that it's
possible to use map() and friends to adjust scalars as they're being fed into
the multiscalar multiplication.

Generalize trait bounds on multiscalar multiplication.

---

README.md
rustdoc-include-katex-header.html
src/edwards.rs
src/lib.rs
src/ristretto.rs

This makes doc.dalek.rs the canonical docs source (vs docs.rs), and replaces the KaTeX files hosted on Cloudflare and the image from githubusercontent with our own hosting.

Use assets from dalek.rs in docs

---

src/backend/avx2/edwards.rs
src/backend/avx2/field.rs

A missing import of the Borrow trait caused the build to break with the
"yolocrypto" feature enabled; this was't caught by CI because the CI machine
that Travis used didn't have AVX2, so the code was never built.
This commit adds the missing import and changes `std` to `core` so that the
AVX2 backend builds with no_std, but this isn't tested and is, actually,
"yolocrypto".

Fix missing avx2 import

---

src/scalar.rs

This PR adds a function for batch `Scalar` inversion. The temporary scalars are erased from the heap in case they're secret.
The `Scalar` code got pretty messy and should be refactored later, but this just minimally adds one function.

Add batch scalar inversion

---

src/ristretto.rs

As noted in the Decaf paper, mapping twice and adding the results ensures a
uniform distribution over the group.  This changes our random point and
hash-to-point functions to do this, matching the Sage script.

Apply the Elligator map twice to ensure a uniform distribution

---

src/backend/avx2/edwards.rs
src/constants.rs
src/edwards.rs
src/ristretto.rs
src/scalar.rs

None of the other Rust functions use `mult`, only `mul`, so we should too.

Rename `multiscalar_mult`->`multiscalar_mul` to match `Mul` traits

---

src/backend/avx2/mod.rs

Just a typo fix; the linebreak broke the Markdown parsing. Also removes an obsolete note.

Fix formatting in AVX2 notes

---

Cargo.toml
build.rs
src/backend/avx2/constants.rs
src/backend/avx2/edwards.rs
src/backend/avx2/field.rs
src/lib.rs

This change required some work, because the to-be-stabilized SIMD functions
don't allow non-constant `imm8`s.  Previously, the `stdsimd` functions had a
constifying macro that ensured that the immediates were known.  The dalek code
used this to build helper functions which would be inlined into different
places where the immediates were known.  Unfortunately, since constexprs aren't
fully supported in Rust yet, this is done by a hidden compiler attribute, and
there's no way to propagate constness.
To deal with this, some of the functions are specialized (e.g.,
`square_and_negate_D` instead of taking a mask), and others use an enum.

Move from external `stdsimd` crate to `core::{arch, simd}` intrinsics

---

src/backend/avx2/edwards.rs

The AVX2 backend broke on recent nightlies due to a type inference failure. This fixes it by adding some hints for the solver.

Fix build on recent nightlies (was broken due to type inference failure)

---

src/edwards.rs
src/ristretto.rs
src/scalar.rs

This PR implements the [Product](https://doc.rust-lang.org/std/iter/trait.Product.html) and [Sum](https://doc.rust-lang.org/std/iter/trait.Sum.html) traits for Scalar.
Partially resolves #131 
I made this PR before implement the Sum trait on the other types so that you can comment on my code before trying to implement the other traits. If you would like me completely close issue #131 before making a PR just tell me.

Implement Product and Sum traits

---

Cargo.toml

When building with [Rust SGX SDK](https://github.com/baidu/rust-sgx-sdk) `byteorder` was pulling in `std` crate which conflicted with `sgx_tstd`. Disabling default features in `byteorder` prevents this.

Disable default features in byteorder dependency to be no_std-compatible

---

.travis.yml
Cargo.toml
README.md
build.rs
src/backend/avx2/mod.rs
src/backend/avx2/scalar_mul/mod.rs
src/backend/mod.rs
src/constants.rs
src/edwards.rs
src/field.rs
src/lib.rs
src/montgomery.rs
src/ristretto.rs
src/scalar.rs
src/scalar_mul/mod.rs

Each backend can now be selected by an individual feature:
- `u32_backend` for `backend::u32`;
- `u64_backend` for `backend::u64`;
- `avx2_backend` for `backend::avx2`;
The `u64_backend` is selected by default, since most people use X64 and we have
no way to select based on target (see discussion in #126).  However, these
changes mean that it is possible to select the backend explicitly, and if we
had the ability to select target-default features, we could do so easily.
This addresses #126 as best as is possible with current Rust features.

Rework backend selection logic.

---

Cargo.toml
benches/dalek_benchmarks.rs
src/lib.rs
src/montgomery.rs
src/ristretto.rs
src/scalar.rs

This specifies the git repository, because `impl CryptoRng for OsRng` was only
added after the last pre-release (in https://github.com/rust-lang-nursery/rand/pull/414)
Once the 0.5 version of `rand` is released, we can edit this commit to remove
the git dependency, and then merge it.
Closes #132

[WIP] upgrade to rand 0.5

---

Cargo.toml

It was previously using pre-release version 0.5.0-pre.2

Upgrade rand to (non-pre)release version 0.5

---

.travis.yml
Makefile
README.md
build.rs
docs/avx2-notes.md
src/backend/avx2/constants.rs
src/backend/avx2/edwards.rs
src/backend/avx2/field.rs
src/backend/avx2/scalar_mul/straus.rs
src/backend/mod.rs
src/lib.rs

This changeset rewrites the AVX2 code from a proof-of-concept to something that matches the quality standards of the rest of our code.
It also documents the formulas used, the implementation strategy, the design tradeoffs, and the coefficient bounds.
It removes the `yolocrypto` flag from the `avx2_backend`.
Closes #142.

Refactor AVX2 code and remove its "yolocrypto" designation

---

README.md
src/edwards.rs
src/field.rs
src/ristretto.rs

Summary of changes:
- Add description of safety guarantees to the README (closes #157)
- Remove various FIXME notes
- Add missing Ristretto double-base-vartime function
- Fix ExtendedPoint validity check to check all coordinates

More pre 1.0 cleanups

---

Cargo.toml
benches/dalek_benchmarks.rs
src/backend/avx2/edwards.rs
src/edwards.rs
src/ristretto.rs
src/scalar.rs
src/traits.rs

Unfortunately, Rust selects `i32` as the type for an integer literal
when the literal has no other type constraints.  This means that someone
cannot write `Scalar::from(1)`, as Rust will choose `i32` as the type for
`1`, and we don't `impl From<i32> for Scalar`.
We could implement `From` conversions for signed integers, but since
`Scalar` operations should be constant-time by default, this would
require us to extract the sign bit of the integer and use it to
conditionally select between the positive and negative of Scalar
constructed from the value bits.  This is more expensive than the
unsigned operation, and I don't think it's what anyone really wants.
Making API consumers specify that their literals are unsigned is
slightly annoying, but better than the above alternative.
It would also …

Replace Scalar::from_u64 with From impls

---

src/scalar.rs

This lets us do, e.g.:
```rust
use clear_on_drop::clear::Clear;
#[derive(Default)]
pub struct SecretKey(pub(crate) Scalar);
impl Drop for SecretKey {
fn drop(&mut self) {
self.clear();
}
}
```

Impl Default for Scalar

---

.travis.yml
Cargo.toml
build.rs
src/backend/avx2/scalar_mul/straus.rs
src/backend/mod.rs
src/edwards.rs
src/field.rs
src/lib.rs
src/montgomery.rs
src/prelude.rs
src/ristretto.rs
src/scalar.rs
src/scalar_mul/straus.rs

This change provides a common convention for using allocator-dependent features with:
```rust
#![cfg(feature = "alloc")]
```
When available, `Vec` is imported consistently as `prelude::Vec`, which means modules that need access to `Vec` can simply do:
```rust
use prelude::*;
```
...and if an allocator is available, `Vec` will be in the crate prelude.
This allows all `alloc` vs `std` gating to be handled in `lib.rs`, `build.rs`, and `prelude.rs` so the rest of the codebase doesn't have to do any gating whatsoever.

Unify `alloc` and `std` cargo features

---

src/ristretto.rs

Pretty sure this was just a typo (based on the signature of the function and the code for `random`), so I skipped opening an issue.
Current code basically just computes the same encoding twice instead of sampling from different domains.

Fix distribution of curve points for hashing to Ristretto points.

---

Cargo.toml

As pointed out by @ruuda:
> This is more of a problem with `#[feature]` in Rust; once a feature becomes
> stable, having `#[feature]` becomes an error, so it is not easy to depend on a
> feature on nightly, and then have the same code work on stable once the feature
> is stabilized.
The earliest `byteorder` version without a `#[feature]` is `1.2.3`, so we
require any higher version than that one.
Closes #184.
Closes #186.

Bump byteorder version to avoid breaking on stable

---

Cargo.toml
build.rs
src/lib.rs
src/ristretto.rs
src/scalar.rs

Vicariously updates to `generic-array` 0.12, however this change also removes `generic-array` as a direct dependency, as it can be sourced from the `digest` crate.

Update to digest 0.8 and sha2 0.8

---

src/constants.rs
src/edwards.rs
src/field.rs
src/ristretto.rs

This removes an unnecessary extra square root in the Elligator code and simplifies the square root handling.

Refactor square root computations and Elligator

---

src/montgomery.rs

Based on the code snippet referenced in issue #207 I implemented the `Default` & `Identity` trait for `MontgomeryPoint`.
The `Default` trait allows us to zero `MontgomeryPoint` values with `clear` on `drop`. I decided to implement this using the `identity` function.
It appeared to me, based on the code, that `MontgomeryPoint`s do have an identity value.
```rust
/// Convert this `EdwardsPoint` on the Edwards model to the
/// corresponding `MontgomeryPoint` on the Montgomery model.
///
/// Note that this is a one-way conversion, since the Montgomery
/// model does not retain sign information.
pub fn to_montgomery(&self) -> MontgomeryPoint {
// We have u = (1+y)/(1-y) = (Z+Y)/(Z-Y).
//
// The denominator is zero only when y=1, the identity point of
// the Edwards curve.  Since 0.invert() = …
```

Default & Identity trait for MontgomeryPoint

---

src/ristretto.rs

The code was correct, but with different variables than the explicit formulas.

Fix variable naming in Ristretto decoding formulas

---

src/field.rs

Fix two typos in FieldElement::invsqrt documentation

---

src/edwards.rs

Fix comment on Montgomery conversion.

---

Cargo.toml
benches/dalek_benchmarks.rs
build.rs
src/lib.rs
src/montgomery.rs
src/ristretto.rs
src/scalar.rs

You don't have to depend on the whole `rand`, instead `rand_core` and `rand_os` can be used.

Replace rand with rand_core+rand_os

---

src/ristretto.rs

Rng was designed to support both &mut and owned usage like this.
It's slightly odd to do this on a method since Borrow exists for that, but this helps a lot with data types so one may as well use it.

Support passing both borrowed and owned Rngs

---

src/ristretto.rs
src/scalar.rs

One fix to https://github.com/dalek-cryptography/curve25519-dalek/issues/232

Revert #219.

---

src/backend/serial/u32/constants.rs
src/backend/serial/u64/constants.rs

redo of #240.
Simple documentation fix concerning the torsion subgroup `E[8]`.

fix typo in torsion documentation

---

src/edwards.rs

I stumbled on this sentence at [ristretto.group](https://ristretto.group/details/equality.html):
> Equality testing of points on the Edwards curve requires comparing to affine coordinates, which requires an expensive inversion. However, testing whether two points lie in the same coset can be done in projective coordinates, making it actually easier than equality testing in the original non-quotient group.
which led me to check the code here and notice this could be optimized. :smiley_cat:

Check the equality of `EdwardsPoint`s in the projective coordinates

---

Cargo.toml

This is an updated version of #247 with a much more minimal change; it simply turns off default features for the serde dependency.  This was suggested by @tarcieri in #247.  
I had initially tried this, but the lack of no_std support in merlin made it look like it was not sufficient.  With updated merlin in place, it works perfectly in my no_std environment.

Turn off default serde features but keep it as an optional dependency

---

src/backend/serial/scalar_mul/mod.rs
src/backend/serial/scalar_mul/pippenger.rs
src/backend/vector/scalar_mul/mod.rs
src/backend/vector/scalar_mul/pippenger.rs
src/edwards.rs
src/scalar.rs

Currently supported Straus algorithm does not improve performance as input size grows and saturates at ≈4x improvement over naïve multiplication. Pippenger’s algorithm takes advantage of very large amount of points (>190) by avoiding premultiplication of points and instead placing points in the buckets indexed by the multiplication factor. Then, buckets are cleverly added up to have their multipliers applied automatically. The process is repeated for each "digit" (that are 6 to 8 bits wide, depending on number of input points). As a result, the cost of multiplication grows slower than linearly with respect to the input size. For 1024 points Pippenger is >40% faster than Straus.
To make the gains more relatable:
0. Batch verification of less than 100 Schnorr signatures is unchanged — …

Pippenger multiscalar multiplication algorithm

---

src/backend/serial/scalar_mul/pippenger.rs
src/backend/serial/scalar_mul/precomputed_straus.rs
src/backend/serial/scalar_mul/straus.rs
src/backend/serial/scalar_mul/vartime_double_base.rs
src/backend/vector/scalar_mul/pippenger.rs
src/backend/vector/scalar_mul/precomputed_straus.rs
src/backend/vector/scalar_mul/straus.rs
src/backend/vector/scalar_mul/vartime_double_base.rs
src/edwards.rs
src/scalar.rs

The Pippenger implementation in 1.2.0 (yanked) had a bug, diagnosed by @oleganza; at the largest problem sizes (using w=8), the signed digits fill the value range of an i8, and so doing computation on them to calculate the bucket index could hit an overflow.
The CI missed catching this because the test suite didn't check all the problem sizes, which I fixed in this PR.  Adding a check that the multiscalar functions work on manually-constructed extremal scalar values (which are allowed by the `Scalar` type for X/Ed25519 compatibility but aren't used as inputs to the multiscalar functions) revealed a bug in the NAF-using computation, which has no security content but has been present since the first version of the library (cc @isislovecruft); there's more details in the commit messages.

Pippenger bugfix

---

src/backend/vector/avx2/mod.rs
src/backend/vector/ifma/mod.rs
src/backend/vector/mod.rs

Since https://github.com/rust-lang/rust/pull/60938 the path root changed and
these new paths are required to compile on nightly.
Closes #268.

Update doc(include) paths.

---

src/edwards.rs
src/field.rs

The comment link (`https://doc-internal.dalek.rs/curve25519_dalek/curve_models/index.html`) for `curve_models` mismatch the actual link：`https://doc-internal.dalek.rs/curve25519_dalek/backend/serial/curve_models/index.html` .

`curve_models` Comment fix

---

src/scalar.rs
src/window.rs

A Quarkslab audit (to be published shortly) looked through the `curve25519-dalek` source code; this PR fixes the issues they identified.
The only serious one is that, although the rest of the `Scalar` API works with canonical scalars, the API has an "invariant loophole", `Scalar::from_bits`, which allows constructing non-reduced scalars for use in, e.g., X/Ed25519, which mandate the use of non-reduced scalars.  
However, although the group operations (scalar, point) were designed to operate on non-reduced scalars, this was not true of (scalar, scalar) addition and subtraction, and so it was possible to use the API to explicitly construct large, unreduced `Scalar`s via `from_bits` and then perform additions and subtractions which compute incorrect results.  This is now fixed, with tests …

Fix issues found in Quarkslab audit

---

src/backend/vector/avx2/mod.rs
src/backend/vector/ifma/mod.rs
src/backend/vector/mod.rs

Currently the library doesn't compile on `nightly` when the `avx2_backend` is enabled; this PR fixes it by fixing the links to the relevant docs.

Fix link to AVX2 docs

---

build.rs
src/backend/vector/ifma/field.rs
src/lib.rs

Closes #256.  This is a work-in-progress.

Use upstream intrinsics

---

src/edwards.rs

The function `FieldElement::sqrt_ratio_i` always returns a positive root
by definition. Therefore the test for negativity in the edwards point
decompression function always returns false and we only need to flip its
sign if `compressed_sign_bit` is set.

Remove unneeded check for negativity in edwards point decompression

---

benches/dalek_benchmarks.rs
src/backend/serial/scalar_mul/pippenger.rs
src/backend/serial/scalar_mul/precomputed_straus.rs
src/backend/serial/scalar_mul/straus.rs
src/backend/vector/scalar_mul/pippenger.rs
src/backend/vector/scalar_mul/precomputed_straus.rs
src/backend/vector/scalar_mul/straus.rs
src/edwards.rs
src/ristretto.rs
src/scalar.rs

Fixes:
- matches that boil down to a ? operator
- clippy lints not against the repo's style
See individual commit messages

Small rust fixes

---

Cargo.toml
src/edwards.rs
src/montgomery.rs
src/ristretto.rs
src/scalar.rs

Adds length checks to the serde-bincode tests, ensuring that the serde `Serialize` and `Deserialize` implementations use fixed-length Serde tuples, rather than variable-length byte arrays.  This flaw in data modeling was pointed out by Trevor Perrin.
This is a breaking change to the serialization format.  It fixes it so that the Serde encoding can match the conventional encoding of each type of object, and so that Serde can be used with no overhead -- when using serde-bincode, the Serde encoding now matches the manual encoding.
Finally, it fills in a missing serde impl for `MontgomeryPoint`.
Closes #265, cf. https://github.com/dalek-cryptography/curve25519-dalek/issues/265#issuecomment-536132620

Fix serde data modeling.

---

Cargo.toml
src/backend/serial/curve_models/mod.rs
src/backend/serial/scalar_mul/straus.rs
src/backend/serial/u32/field.rs
src/backend/serial/u32/scalar.rs
src/backend/serial/u64/field.rs
src/backend/serial/u64/scalar.rs
src/backend/vector/avx2/field.rs
src/backend/vector/scalar_mul/straus.rs
src/lib.rs
src/scalar.rs
src/window.rs

`zeroize` is WASM-friendly as it has no dependencies on C compilers.
Instead uses Rust's own volatile write semantics and compiler fences to ensure zeroization is not elided by the compiler.

Switch from `clear_on_drop` to `zeroize` (fixes #281)

---

Cargo.toml

Of these only `rand_core` is included in the public API; regardless of `rand`
semver tricks, this is a breaking API change, but the major version is already
bumped to include the Serde serialization fixes for #265.

Update rand_core, rand, rand_os.

---

src/backend/vector/avx2/field.rs

This implementation is broken because the packed_simd types don't implement `Zeroize`.  Tested this manually with the `avx2` backend on `skylake` and with the `ifma` backend on `cannonlake`.

Fix broken build with AVX2.

---

src/backend/serial/u32/constants.rs
src/backend/serial/u64/constants.rs
src/ristretto.rs

This should fix #224. 
The link in that issue refers to a different line in the codebase, so it's possible I have updated the wrong functions.
The values are based on the original calculation, but please double-check them.

Added constants to reduce recalculations in elligator_risteretto_flavor

---

src/ristretto.rs

This test is no longer necessary as it originally had a possibility of failure due to the original implementation of the invsqrt() function in the decompression algorithm.  The failure with the current API is nonexistent.
* FIXES #288.

Remove test for validity of randomly generated RistrettoPoints.

---

Cargo.toml
benches/dalek_benchmarks.rs
src/lib.rs
src/montgomery.rs
src/ristretto.rs
src/scalar.rs

The functionality we were using is now contained in the `rand_core` crate, which we already depend upon.  As far as testing code goes, only benchmarks still depend upon `rand`, as they use `thread_rng`.

Remove dev-dependency on deprecated rand_os crate.

---

src/backend/serial/scalar_mul/variable_base.rs

rustc doesn't seem smart enough to figure out that when doing:
```rust
let mut tmp1 = T;
let mut tmp2 = T;
let mut tmp3 = T;
for i in 0..63 {
// ...
tmp1 = tmp2.double();
tmp3 = tmp1.to_extended();
tmp1 = tmp3 + foo;
}
```
that the tmp2 variable is actually used.  This silences that erroneous warning.

Fix a warning that a temporary value isn't used.

---

Cargo.toml
README.md

This bumps the required `subtle` version to `2.2.1`, which contains those changes.

Remove nightly recommendation now that subtle has stable optimization barriers.

---

Cargo.toml

Note this allows the use of benchmark comparison tooling such as [critcmp](https://github.com/BurntSushi/critcmp).

Bump criterion version

---

src/scalar.rs

`const_fn` is stable since Rust 1.31 (https://github.com/rust-lang/rust/pull/54835) and enables calling `Scalar::from_bits(..)` from other const fn contexts, potentially saving some overhead here and there.
Especially useful in contexts where constants are being built from a bit pattern.
---
My use case is a constructor for a certain large number, where I'd rather start from a slice and set the correct bits that just hardcode in all 32 bytes at once.
I'm not 100% sure about the compatibility guarantees when switching an existing function to `const`, but I imagine it shouldn't interfere anywhere, since the whole test suite still passes.
The other constructors use a call to `.reduce()`, so I didn't bother looking deeper whether they can be made `const` too.

Make Scalar::from_bits a const fn.

---

src/backend/serial/u64/scalar.rs
src/lib.rs

`feature(alloc)` is not needed and removing it allows to compile with stable Rust when the crate `alloc` feature is on.
`println!` was removed in the test as the corresponding test for `u32` does not have it.

Make crate feature alloc work with stable Rust

---

Cargo.toml
src/edwards.rs
src/ristretto.rs

This is helpful for hardening some of our cryptographic implementations
that use Ristretto curve points
Please let me know if you would like this done differently, or if there is
some reason you don't want to use `zeroize_derive`. Thank you!

implement Zeroize trait on Ristretto curve point types

---

Cargo.toml
src/backend/serial/u32/constants.rs
src/backend/serial/u64/constants.rs
src/edwards.rs
src/montgomery.rs

This present PR:
- can be seen as a more conservative variant of PR #326 (it performs no double mapping), 
- implements the vanilla Elligator2 mapping (matching the [draft RFC](https://tools.ietf.org/id/draft-irtf-cfrg-hash-to-curve-10.html) short of the `expand_message_xmd` expansion¹)
- is, as such, subject to the known distribution biases of Elligator2 (see #326 and https://eprint.iacr.org/2014/043 )
While I'm a fan of Ristretto and would definitely advocate for its use over mapping-to-curve25519 in most situations, this present mapping is still useful in cases where compatibility with other libraries is required — the present mapping is compatible with the one performed in [libsignal](https://github.com/signalapp/libsignal-protocol-c/blob/master/src/curve25519/ed25519/additions/elligat …

Elligator2 mapping for curve25519

---

src/edwards.rs
src/ristretto.rs
src/scalar.rs
src/traits.rs
src/window.rs

Merge configurably sized basepoint multiplication lookup tables

---

src/edwards.rs
src/ristretto.rs
src/scalar.rs
src/traits.rs
src/window.rs

Hi!
I've implemented more table sizes for fixed-base scalar multiplication. The motivation here is primarily to allow for memory/time optimisations for signature verifications (cf. https://github.com/isislovecruft/ed25519-dalek/blob/feature/public-key-precomputation_r1/src/traits.rs and https://github.com/isislovecruft/ed25519-dalek/blob/feature/public-key-precomputation_r1/src/precomputed.rs) where a user who needs to verify many signatures with the same public key can dynamically chose to recompute larger/smaller tables, but it's also likely useful for systems which use Chaum-Pedersen commitments or Okamoto commitments or any other NIZK proof/sigma protocol which uses two basepoints.
I've benchmarked this (see my separate `feature/dynamic-tables-sizes-benches` branch) and the results so …

variable-sizes of precomputed tables for basepoint scalar multiplication

---

benches/dalek_benchmarks.rs

- removes usages fo the (deprecated) `bench_function_over_inputs`
- introduces a few benchmark groups.
There's many ways to re-organize benchmark groups, happy to take some feedback in consideration in review.
Sample output:
- [before this PR](https://gist.github.com/eb68ce45c895bf2699da5e80622ead1e)
- [after this PR](https://gist.github.com/93ce32deae4051e617951d9a5a9998fd)

[benchmarks-only] Updates the benchmarks

---

src/backend/serial/u32/constants.rs
src/backend/serial/u64/constants.rs
src/montgomery.rs

cf. https://github.com/dalek-cryptography/curve25519-dalek/pull/336

Trivial cleanups to Elligator2 encoding

---

Cargo.toml

https://github.com/rust-random/rand/blob/master/rand_core/CHANGELOG.md
This new version makes using rand_core on wasm seamless (thanks to the update of getrandom to v0.2)
The crate compiles well with this PR, but since some `rand_core` traits are publicly exposed in this crate's API, this is strictly speaking a breaking change.

Update rand_core to 0.6

---

src/montgomery.rs

This can be used in checks for non-contributory behaviour in protocols
where that is a concern.

Implement Identity for MontgomeryPoint.

---

.github/workflows/rust.yml
CHANGELOG.md
Cargo.toml
README.md

This PR:
* Relaxes `zeroize` to `^1`
* Improves documentation about this crate's MSRV
* Fixes the MSRV tests. Previously they were using the newest deps. But the MSRV should be calculated with respect to the oldest possible deps.
I would like to cut a release soon. According to the MSRV test, our v4.0 will not require an MSRV bump.

Relax zeroize dependency

---

Cargo.toml
src/scalar.rs

Instead of having a dependency on `byteorder` use methods from the
standard library(`{to,from}_le_bytes`).
This addresses the concern in #392

Remove byteorder

---

.github/workflows/rust.yml

actions/checkout@v2 uses Node 12 which will be deprecated by Summer 2023.
Actions from actions-rs also use Node 12 but they are unmaintained, so actions-rs/toolchain is replaced by dtolnay/rust-toolchain and actions-rs/cargo is replaced by manual cargo commands.

Update GitHub actions

---

.github/workflows/rust.yml
src/backend/vector/avx2/constants.rs
src/backend/vector/avx2/edwards.rs
src/backend/vector/avx2/field.rs
src/backend/vector/ifma/constants.rs
src/backend/vector/ifma/edwards.rs
src/backend/vector/ifma/field.rs
src/backend/vector/scalar_mul/pippenger.rs
src/backend/vector/scalar_mul/precomputed_straus.rs
src/backend/vector/scalar_mul/straus.rs
src/backend/vector/scalar_mul/variable_base.rs
src/backend/vector/scalar_mul/vartime_double_base.rs
src/edwards.rs
src/ristretto.rs

It looks like #413 broke the build for AVX2 and AVX-512 backends by not sprinkling enough `crate::` prefixes around. This PR fixes the build. I tested it on a machine with both CPU features available.
It's not great that this breakage was able to happen. As far as I know, though, Github Actions runners do not have AVX2. I'll just have to manually run these tests locally until we have another solution.

Fix AVX2 and AVX-512 builds

---

.github/workflows/rust.yml

The `RUSTFLAGS` were getting applied to build scripts, which caused them to crash with SIGILL.
According to this issue, RUSTFLAGS won't be applied to build scripts when cross-compiling by passing the `--target` attribute:
https://github.com/rust-lang/cargo/issues/4423
This attempts to work around the problem by explicitly passing:
--target x86_64-unknown-linux-gnu

CI: fix `build-simd` job

---

Cargo.toml
src/edwards.rs
src/field.rs
src/lib.rs
src/montgomery.rs
src/ristretto.rs
src/scalar.rs
src/traits.rs

...and one other `alloc` cleanup.
`simd_backend` requires `alloc` and so this combination previously caused a compile error.
Also one additional test that works with an `alloc`-only profile wasn't enabled, causing a warning in this case.
Finally, changes CI to test this configuration.

Fix `simd_backend` + `--no-default-features`

---

src/backend/vector/avx2/mod.rs
src/backend/vector/ifma/mod.rs
src/backend/vector/mod.rs

Previously a now-removed nightly-only feature was used, but now that it's stable, `include_str!` can be used for all of these cases.

Use `include_str!` for `.md` inclusion in rustdoc

---

src/ristretto.rs
src/scalar.rs

This allows the code to compile if you pass it `&mut dyn RngType`,
since trait objects are unsized.
See here for an example of caller code that is simplified by this
change:
https://github.com/mobilecoinfoundation/mobilecoin/pull/1977#discussion_r872906913

Relax Rng trait bounds to allow `?Sized` Rngs

---

.github/workflows/rust.yml
CHANGELOG.md
build.rs
src/backend/serial/mod.rs
src/constants.rs
src/field.rs
src/scalar.rs

Related before-PR-doc (rendered): https://github.com/dalek-cryptography/curve25519-dalek/pull/453#discussion_r1042294155
Thou shall ask: https://github.com/dalek-cryptography/curve25519-dalek/issues/449#issuecomment-1340670829
Thou shall be giveth:
Test cfg matrix / expectation
All selected backends are mutually exclusive.
Auto select `fiat_u32` / `fiat_u64` based on `cfg(target_pointer_width)` - default `fiat_u32` on non-32/64 bits
Auto select `u32` / `u64` based on `cfg(target_pointer_width)` - default `u32` on non-32/64 bits
Selects `fiat_u32` regardless of target_pointer on fiat_backend
Selects `fiat_u64` regardless of target_pointer
Selects `u32` (serial) regardless of target_pointer
Selects `u64` (serial) regardless of target_pointer

Add target u32/u64 backend overrides

---

.github/workflows/rust.yml
CHANGELOG.md
Cargo.toml
build.rs

As discussed in #456 ~~this sets well known defaults for:~~
~~`cfg(target_family = "wasm")`~~ and ~~`cfg(target_arch = "arm")`~~
~~By setting the 64 bit serial arithmetric via `cfg(curve25519_dalek_bits = "64")`~~
EDIT: I've used platforms crate via env TARGET to determine the actual cross target and this now fixes build.rs only.

Fixes `curve25519_dalek_bits` defaults for cross and wasm

---

Cargo.toml
src/ristretto.rs
src/scalar.rs

This is a convenience/marker trait for types which impl `CryptoRng` + `RngCore` which makes the type signatures a little more readable.
It was introduced in `rand_core` v0.6.4 (now pinned as the minimum version)

Use `CryptoRngCore` trait

---

README.md

[Rendered](https://github.com/pinkforest/curve25519-dalek/tree/docs-backend-cfgs)
Documenting
- #456  
- #465 
- #455 
- #454 
Note `fiat` cannot be used in combination with `simd` as I attempted :hankey: and found out :blush: 
- #463
I also thought it is best to document the cross-re-use between target backends between `avx` and `u64`

Document `curve25519_dalek_` `backend` and `bits` selection

---

src/backend/serial/curve_models/mod.rs
src/backend/serial/fiat_u32/field.rs
src/backend/serial/fiat_u64/field.rs
src/backend/serial/u32/constants.rs
src/backend/serial/u32/field.rs
src/backend/serial/u32/scalar.rs
src/backend/serial/u64/constants.rs
src/backend/serial/u64/field.rs
src/backend/serial/u64/scalar.rs
src/backend/vector/avx2/edwards.rs
src/backend/vector/avx2/field.rs
src/backend/vector/ifma/edwards.rs
src/backend/vector/ifma/field.rs
src/constants.rs
src/edwards.rs
src/field.rs
src/montgomery.rs
src/ristretto.rs
src/scalar.rs

For the field element types `FieldElement` and `Scalar`, use inherent constants instead of (non-const) functions to return these constant values.
It's likely the original functions predate support for inherent constants, but now that they're available, they're a better fit for these sort of constant values.

Use inherent constants for `ZERO`, `ONE`, and `MINUS_ONE`

---

CHANGELOG.md
Cargo.toml
src/scalar.rs

~~*NOTE: includes #470 which should be merged first*~~ Merged!
This is helpful for implementing `ff::PrimeField::from_repr`.
Also changes `Scalar::is_canonical` to return `Choice`.

Change `Scalar::from_canonical_bytes` to return `CtOption`

---

Makefile
docs/assets/rustdoc-include-katex-header.html
src/backend/serial/fiat_u32/field.rs
src/backend/serial/fiat_u64/field.rs
src/backend/serial/u32/field.rs
src/backend/serial/u32/scalar.rs
src/backend/serial/u64/field.rs
src/backend/serial/u64/scalar.rs

`make doc` wasn't building after #470 because of missing doc comments and also because `simd_backend` isn't a feature anymore. Fixed those.
Also I edited the docs CSS to display code at the normal size. It always appeared too small to me.

Fixed doc build

---

Cargo.toml

Current build [fails](https://docs.rs/crate/curve25519-dalek/4.0.0-pre.3/builds/700411) because `simd_backend` was accidentally listed as a feature. This should fix it, but I haven't tested it myself.

Fixed docsrs flags in Cargo.toml

---

build.rs

- Whilst going through the Neon backend I found out I forgot to allow a placeholder for clippy in build.rs

Fix clippy for build.rs

---

Cargo.toml
README.md
src/lib.rs

[Rendered](https://docs.rs/crate/test-curve25519-dalek/4.0.0-pre.16)
Just needed the separate` RUSTCFLAGS` which are `rustc-flags = []` in docs.rs meta (regular thing with `RUSTDOCFLAGS`)

Fix docs.rs release pre.5

---

.github/workflows/rust.yml
Cargo.toml
README.md
src/backend/serial/curve_models/mod.rs
src/backend/serial/fiat_u32/field.rs
src/backend/serial/fiat_u64/field.rs
src/backend/serial/u32/field.rs
src/backend/serial/u32/scalar.rs
src/backend/serial/u64/field.rs
src/backend/serial/u64/scalar.rs
src/edwards.rs
src/montgomery.rs
src/ristretto.rs
src/scalar.rs
src/window.rs

The `zeroize` crate provides a defense against memory read oracles which typically arise from memory unsafety.
Pure Rust programs may not benefit from `zeroize`, and in certain cases the unsafe code used by `zeroize` may be more concerning.
This commit makes `zeroize` into an optional feature so users may elect to disable it if they so desire.

Make `zeroize` an optional dependency

---

.github/workflows/rust.yml
CHANGELOG.md
Cargo.toml
README.md
src/backend/serial/scalar_mul/straus.rs
src/scalar.rs

Previously `alloc` implicitly activated `zeroize` via `zeroize/alloc`.
This commit switches to weak feature activation as added in Rust 1.60, only activating `zeroize/alloc` if the `zeroize` dependency is explicitly activated (which it is by default).

Weakly activate `zeroize?/alloc`; MSRV 1.60

---

.github/workflows/rust.yml

We currently don't have any checks that this crate builds on a `no_std` target.
While `curve25519-dalek` itself doesn't link `std`, it uses dependencies which could potentially link `std`, so it's important to have a job to check that the crate builds on a `no_std` target to ensure feature activation doesn't accidentally flip on the `std` feature of one of those dependencies unintentionally.
This adds a job which checks the crate builds on a `thumbv7em-none-eabi` target which has no `std` implementation.

CI: add `build-nostd` job

---

Cargo.toml
src/lib.rs

The recommendation to set this has been removed from the Rust API guidelines:
https://github.com/rust-lang/api-guidelines/pull/230
It used to be used by docs.rs, but docs.rs now unconditionally sets the `--extern-html-root-url` parameter of rustdoc which overrides it, making it no longer needed and superfluous.

Don't set `html_root_url`

---

.github/workflows/rust.yml

This action is located at:
https://github.com/RustCrypto/actions/blob/master/cross-install/action.yml
It's used across the RustCrypto project for installing `cross` in CI.
Installation is performed by fetching a pinned binary release from:
https://github.com/cross-rs/cross/releases/
This eliminates problems that might occur when using `cargo install` such as:
https://github.com/dalek-cryptography/curve25519-dalek/actions/runs/3786735408/jobs/6437902657
It's also marginally faster.

CI: use RustCrypto/actions/cross-install

---

src/edwards.rs
src/montgomery.rs
src/ristretto.rs
src/scalar.rs

Does a pass on adding `const` to methods where it's possible.
Closes #493.

Expand `const fn` support

---

.github/workflows/rust.yml
CHANGELOG.md
Cargo.toml
README.md
src/backend/serial/u32/constants.rs
src/backend/serial/u64/constants.rs
src/constants.rs
src/edwards.rs
src/ristretto.rs
src/scalar.rs
src/window.rs

This is the name we adopted for a similar feature in @RustCrypto.
It's a bit less jargony and also leaves the door open in the future to other types of precomputed tables.

Rename `basepoint-tables` to `precomputed-tables`

---

src/edwards.rs
src/ristretto.rs

The `from_slice` methods on `CompressedEdwardsY` and `CompressedRistretto` both previously panicked if the slice was the wrong length.
This changes them to be fallible, returning `TryFromSliceError` in the event the slice is the wrong length.
It also adds a `TryFrom<&[u8]>` impl for each of these types which calls the corresponding `from_slice` method.

Make `from_slice` methods fallible; add `TryFrom<&[u8]>`

---

Cargo.toml
benches/dalek_benchmarks.rs
src/backend/serial/scalar_mul/vartime_double_base.rs
src/backend/serial/u32/constants.rs
src/backend/serial/u64/constants.rs
src/backend/vector/avx2/constants.rs
src/backend/vector/ifma/constants.rs
src/backend/vector/mod.rs
src/backend/vector/scalar_mul/vartime_double_base.rs
src/window.rs

We still had some size-8 NAF tables lying around for the `aA + bB` vartime procedure. This puts those tables behind the `precomputed-tables` feature gate.
New bench results for `precomputed-tables` on my M1 machine, using u64 serial backend:
65% speedup on fixed-base mul, 9% speedup on `aA + bB` vartime mul. And the `.rlib` file went from 1.4MB to 758KB (54% of original).
Weirdly, there was a 9% _slowdown_ on vartime fixed-based multiscalar mul over 512 elems, but a 6% speedup on the same thing over 1024 elements. Go figure.

Feature-gated more precomputed tables

---

src/lib.rs

Re-exports the following commonly used types from their respective modules to the toplevel of the crate, which makes them easier to access:
- `EdwardsPoint`
- `MontgomeryPoint`
- `RistrettoPoint`
- `Scalar`

Re-export commonly used types from toplevel

---

build.rs

Fixes #508 
Supercedes #509 
Desired behaviour is to require explicit setting in case of custom targets and give our helpful error message.
Also clears out the unwrap for missing standard TARGET in case of being used in non-Cargo build system.

Fix error for custom targets

---

src/edwards.rs
src/ristretto.rs
src/scalar.rs

Serde errors are not simple enums; they format a full error string from their arguments. It's worth not doing that up front.

Use ok_or_else instead of ok_or in serde decoding

---

build.rs

Fixes #515 by @ryankurte fix
Fixes #511 thanks @jcape for pointing out the warning message
We fix the cross build with override which was broken due to rustc not relaying curve cfg's.
Given it is difficult to use we also default to `cfg(curve_25519_dalek_bits="32")` with a warning instead of a hard error.
Slightly vary of using `CARGO_CFG_` given rustc removes them in build.rs for `#[cfg()]` beyond target `cfg` set.
Cc/ @jrose-signal
Test matrix on x86_64-unknown-linux-gnu native host:
$ rustup default 1.60 ; cargo clean
$ rustup default stable ; cargo clean
$ rustup default nightly ; cargo clean
$ cargo build
$ env RUSTFLAGS='--cfg curve25519_dalek_bits="64"' cargo build
$ env RUSTFLAGS='--cfg curve25519_dalek_bits="64"' cargo build --target wasm32-unknown-unknown
$ env RUSTFLAGS='--cfg …

Fixes cfg with target from env

---

CHANGELOG.md
Cargo.toml
README.md

- Update manifest
- Update CHANGELOG - [Rendered](https://github.com/pinkforest/curve25519-dalek/blob/chore-release-400-rc2/CHANGELOG.md)
- Update README - [Rendered](https://github.com/pinkforest/curve25519-dalek/tree/chore-release-400-rc2)
- Minor dep bump (these get selected anyways just reflects the reality)
- Adds tracking issue mention about remaining pending potential API breaking change/s for 4.0.0:
- https://github.com/dalek-cryptography/curve25519-dalek/issues/521
x25519 and ed25519 would have reflctive rc.2 releases so this would be across-the-crates sync release easy to :anchor: on.
Current use of release candidates is at ~10% and it is safe to do across-all-the-crates rc.2 release to increase use/migration.

chore: Release 4.0.0-rc.2

---

src/scalar.rs

The exponent defining the upper bound of the result of the `mods` operation in the docs should be `w-1`, not `w`. See the screenshot below for reference.
The implementation is not affected by this error.
This PR fixes the value of the exponent in the docs.

fix: Use the correct exponent in the description of the `mods` operation

---

src/constants.rs
src/edwards.rs
src/field.rs
src/montgomery.rs
src/ristretto.rs
src/scalar.rs
src/traits.rs

Leverages the `From<Choice>` impl for `bool` where applicable instead, which results in clearer logic which more closely matches `bool`.

Replace `unwrap_u8` with `into`

---

.github/workflows/rust.yml
Cargo.toml
Makefile
README.md
build.rs
src/backend/mod.rs
src/backend/serial/mod.rs
src/backend/serial/u64/constants.rs
src/backend/vector/avx2/edwards.rs
src/backend/vector/avx2/field.rs
src/backend/vector/avx2/mod.rs
src/backend/vector/ifma/edwards.rs
src/backend/vector/ifma/field.rs
src/backend/vector/ifma/mod.rs
src/backend/vector/mod.rs
src/backend/vector/packed_simd.rs
src/backend/vector/scalar_mul/mod.rs
src/backend/vector/scalar_mul/pippenger.rs
src/backend/vector/scalar_mul/precomputed_straus.rs
src/backend/vector/scalar_mul/straus.rs
src/backend/vector/scalar_mul/variable_base.rs
src/backend/vector/scalar_mul/vartime_double_base.rs
src/constants.rs
src/edwards.rs
src/lib.rs
src/ristretto.rs
src/scalar.rs

This PR makes the following changes:
* The backend used is now by default autodetected at runtime based on the features supported by the CPU.
* If the appropriate target feature is available at compile time (through `-C target_feature`) then that particular feature is assumed to be always available (courtesy of the `cpufeatures` crate), and we won't try to detect whether it's available at runtime.
* If the target doesn't support runtime autodetection (e.g. `x86_64-fortanix-unknown-sgx`) then no runtime autodetection will take place (courtesy of the `cpufeatures` crate)
* Cargo features are now used to control whether a particular SIMD backend can be used. This is a necessary, but not sufficient, requirement for a backend to be used. (The idea here is to let the users *disable* those …

Runtime backend autodetection

---

ed25519-dalek/src/hazmat.rs
ed25519-dalek/src/signing.rs
ed25519-dalek/src/verifying.rs
ed25519-dalek/tests/x25519.rs

The reason `ExpandedSecretKey` needs a private `scalar_bytes` field is to retain the canonical scalar bytes as output by SHA-512 during key expansion so they can be serialized by the `to_bytes` method.
However, `ExpandedSecretKey`s should not be serialized to the wire.
Removing this method allows the private field to be removed, which allows `ExpandedSecretKey` to be constructed entirely from public fields. This provides an alternative to #544 for use cases like Ed25519-BIP32 where the private scalar is derived rather than clamped from bytes.
One other change is needed: `to_scalar_bytes` was changed to `to_scalar` as the canonical scalar bytes are no longer retained, however this has no impact on its main use case, X25519 Diffie-Hellman exchanges, where the `Scalar` should NOT be written …

ed25519-dalek: remove `ExpandedSecretKey::to_bytes`

---

x25519-dalek/Cargo.toml
x25519-dalek/README.md
x25519-dalek/src/x25519.rs

Now that `curve25519-dalek` version 4 has been released and I couldn't find any outstanding PRs/Issues can version 2 of `x25519-dalek` be released?
Also, can https://github.com/dalek-cryptography/x25519-dalek redirect to here? It's pretty confusing

Stabilize x25519-dalek version 2

---

ed25519-dalek/Cargo.toml
ed25519-dalek/src/signing.rs

Moved over from https://github.com/dalek-cryptography/ed25519-dalek/pull/306

ConstantTimeEq and PartialEq for SigningKey

---

ed25519-dalek/src/signing.rs

Allows to get a reference to the secret bytes without making a copy.

ed: Add `SigningKey::as_bytes`

---

curve25519-dalek/src/backend/serial/curve_models/mod.rs
curve25519-dalek/src/backend/serial/fiat_u32/field.rs
curve25519-dalek/src/backend/serial/fiat_u64/field.rs
curve25519-dalek/src/backend/serial/scalar_mul/pippenger.rs
curve25519-dalek/src/backend/serial/u32/field.rs
curve25519-dalek/src/backend/serial/u32/scalar.rs
curve25519-dalek/src/backend/serial/u64/field.rs
curve25519-dalek/src/backend/serial/u64/scalar.rs
curve25519-dalek/src/backend/vector/avx2/edwards.rs
curve25519-dalek/src/backend/vector/avx2/field.rs
curve25519-dalek/src/backend/vector/scalar_mul/pippenger.rs
curve25519-dalek/src/edwards.rs
curve25519-dalek/src/field.rs
curve25519-dalek/src/lib.rs
curve25519-dalek/src/montgomery.rs
curve25519-dalek/src/ristretto.rs
curve25519-dalek/src/scalar.rs
curve25519-dalek/src/traits.rs
curve25519-dalek/src/window.rs

Adds a lints section to the top of lib.rs with the following:
#![warn(
clippy::unwrap_used,
missing_docs,
rust_2018_idioms,
unused_lifetimes,
unused_qualifications
)]
`warn` is used instead of `deny` to prevent the lints from firing during local development, however we already configure `-D warnings` in CI so if any lint fails on checked-in code, it will cause a CI failure.
This commit also fixes or explicitly allows any current violations of these lints. The main ones were:
- `clippy::unwrap_used`: replaces usages of `unwrap` with `expect`
- `rust_2018_idioms`: no implicit lifetimes, which were present on usages of `core::fmt::Formatter`
- `unused_lifetimes`: corrects a few instances

Expand lints

---

curve25519-dalek/src/backend/serial/mod.rs

We have a lot of backend types leaking via the public API, including e.g. `FieldElement51`:
https://docs.rs/curve25519-dalek/latest/curve25519_dalek/backend/serial/u64/field/struct.FieldElement51.html
At the very least, these types shouldn't be visible in the rustdoc.
This PR hides them from the docs, but ideally we would hide them completely from the public API (which might technically be considered a breaking change, but IMO leaking them at all is a bug).

curve: add `doc(hidden)` to serial backend modules

---

curve25519-dalek/Cargo.toml
ed25519-dalek/Cargo.toml

noticed this from https://deps.rs/crate/ed25519-dalek

chore: update dev deps

---

ed25519-dalek/src/signing.rs

Previously the variable names referred to `public` and `secret` which do not exist. Update them to `verifying_key` and `secret_key`.
This PR replaces https://github.com/dalek-cryptography/ed25519-dalek/pull/313

Fix variable names in the invariant description

---

curve25519-dalek/Cargo.toml
curve25519-dalek/src/backend/serial/fiat_u32/field.rs
curve25519-dalek/src/backend/serial/fiat_u64/field.rs
curve25519-dalek/src/backend/serial/u32/constants.rs
curve25519-dalek/src/backend/serial/u32/field.rs
curve25519-dalek/src/backend/serial/u64/constants.rs
curve25519-dalek/src/backend/serial/u64/field.rs

I have an outstanding PR that proposes some breaking changes to fiat-crypto, see mit-plv/fiat-crypto#1623. Briefly, it introduces new structures to replace different type aliases for each field element representation. Encoding this in the type system is intended to prevent misuse of functions that require "tight" preconditions on their inputs' ranges. I'm opening this PR for a future crate upgrade early, with a `[patch.crates-io]` stanza, to test out the breaking change, and for temporary use in fiat-crypto's integration tests. If this looks good, I can back out the patch stanza when `fiat-crypto` is released and mark it ready for review.

Adapt to new types introduced in fiat-crypto 0.2

---

curve25519-dalek/CHANGELOG.md
curve25519-dalek/src/constants.rs
curve25519-dalek/src/edwards.rs

Deprecates `BASEPOINT_ORDER` from pub API constants
Redirect internally to avoid deprecation errors

Deprecate `BASEPOINT_ORDER` from pub API consts

---

curve25519-dalek/CHANGELOG.md
curve25519-dalek/Cargo.toml
curve25519-dalek/src/scalar.rs

The char_le_bits function is a hack I don't legitimately recommend. I just felt it'd be better to make a PR, which works, than to solely file an issue requesting it as a feature.

Add PrimeFieldBits support to Scalar

---

curve25519-dalek-derive/README.md

On a MacBook M1, I noticed `cargo test` in the workspace root fails. It fails due to the references to `#[target_feature(enable = "avx2")]` in the `README.md` for `curve25519-dalek-derive`.
This PR avoids the test failure by adding conditional compile statements on the usages of `target_feature`. `cfg` statements are added as hidden lines in the examples and so they will not appear in `cargo doc`. Hidden lines will appear when looking at the README on GitHub.

Avoid cargo test -p curve25519-dalek-derive failure on ARM

---

ed25519-dalek/Cargo.toml

The `signature` crate contains unstable, minor version-gated functionality.
The v2.1 release did not change any of that, and only added new functionality. So it's safe to relax the requirement for `signature` to `>=2.0, <2.2`.

ed25519: loosen `signature` crate dependency

---

ed25519-dalek/Cargo.toml

Like #582, there is a new release of `signature` ([v2.2.0](https://crates.io/crates/signature/2.2.0)) which contains no breaking changes from ed25519-dalek's perspective. The main notable one is it bumps MSRV to 1.60, which so also happens to also be ed25519-dalek's MSRV.
This commit loosens the version requirement to allow `>=2.0, <2.3` to allow the `signature` 2.2 series.

ed25519: loosen `signature` crate dependency again

---

ed25519-dalek/CHANGELOG.md
ed25519-dalek/Cargo.toml
ed25519-dalek/src/signing.rs
ed25519-dalek/tests/x25519.rs

As mentioned in the conversation in https://github.com/dalek-cryptography/curve25519-dalek/issues/565, it is currently not clear how you would use a clamped and reduced scalar from `SigningKey::to_scalar()` to build an x25519 keypair. In fact, the test code in that thread shows that `x25519_dalek::PublicKey::from(StaticScalar::from(sk.to_scalar().to_bytes()))` does not match the ed25519 public key. This is because the second public key computation does clamping again, so it's clamp -> reduce -> clamp, which is not a no-op.
This PR replaces `SigningKey::to_scalar()` with `SigningKey::to_scalar_bytes()`, which returns the unreduced scalar bytes determined by the ed25519 secret key. This is actually how things used to be before https://github.com/dalek-cryptography/curve25519-dalek/pull/545, …

ed: Change `SigningKey::to_scalar` back to `SigningKey::to_scalar_bytes`

---

ed25519-dalek/CHANGELOG.md
ed25519-dalek/Cargo.toml

#598 merits a new release, and #599 added functionality, so we need a minor version bump.

ed: Prep to release v2.1.0

---

ed25519-dalek/src/signing.rs
ed25519-dalek/src/verifying.rs

This is a slight improvement to the deserialisation code for `SigningKey` and `VerifyingKey`.
The default implementations of `visit_borrowed_bytes` and `visit_byte_buf` [forward to](https://docs.rs/serde/1.0.192/serde/de/trait.Visitor.html#method.visit_borrowed_bytes) `visit_bytes`, but only `visit_borrowed_bytes` was implemented for the `{Signing,Verifying}KeyVisitor`.  This means that `{Signing,Verifying}Key`s can only be deserialised from borrowed byte arrays, but not from [owned or transient byte arrays](https://serde.rs/data-model.html).  Example:
```rust
let bytes = base16ct::lower::decode_vec(
"66b1419fae979516fb3807dda1b05026b2570a7ab2190254e524af4f0934ddd2",
)
.unwrap();
let d = serde::de::value::BorrowedBytesDeserializer::<serde::de::value::Error>::new(&bytes); …
```

{Signing,Verifying}KeyVisitor: visit_borrowed_bytes -> visit_bytes

---

ed25519-dalek/README.md

The markdown formatting was a bit broken (`[` and `(` used in wrong order). This tiny PR fixes it.

doc: Fix markdown PR reference

---

curve25519-dalek/src/lib.rs

Addresses #618.
This PR fixes the failing build on the latest Rust nightly compiler `rustc 1.78.0-nightly (f067fd608 2024-02-05)`.
The `stdsimd` feature has been split into separate features in the latest Rust nightly compiler and its usage needs to be updated to use `#![feature(stdarch_x86_avx512)]` instead.
See https://github.com/rust-lang/stdarch/pull/1486 and https://github.com/rust-lang/rust/issues/111137.

Fix nightly build

---

curve25519-dalek/CHANGELOG.md
curve25519-dalek/Cargo.toml
ed25519-dalek/CHANGELOG.md
ed25519-dalek/Cargo.toml
x25519-dalek/CHANGELOG.md
x25519-dalek/Cargo.toml

curve,ed,x: Bump patch version to reflect fix to nightly SIMD build

---

curve25519-dalek/src/traits.rs

Recent nightlies have started emitting a dead code lint which is breaking the build: https://github.com/dalek-cryptography/curve25519-dalek/actions/runs/7873600894/job/21481401663?pr=624#step:4:152

curve: mark `ValidityCheck` trait as `allow(dead_code)`

---

ed25519-dalek/src/verifying.rs
ed25519-dalek/tests/ed25519.rs

Add VerifyingKey::to_edwards

---

ed25519-dalek/README.md

Fixes two minor spelling mistakes which I have encountered while reading the `ed25519-dalek/README.md`.

Fix minor spelling mistakes

---

curve25519-dalek/src/backend/serial/scalar_mul/pippenger.rs
curve25519-dalek/src/backend/vector/avx2/edwards.rs
curve25519-dalek/src/edwards.rs
curve25519-dalek/src/field.rs
curve25519-dalek/src/ristretto.rs
curve25519-dalek/src/scalar.rs
curve25519-dalek/src/traits.rs
ed25519-dalek/src/batch.rs
ed25519-dalek/src/signature.rs
ed25519-dalek/src/verifying.rs
ed25519-dalek/tests/ed25519.rs

Fix new nightly redundant import lint warns

---

ed25519-dalek/src/lib.rs

The main example doesn't explicitly indicate that the `rand_core` feature is required, and rust gives confusing error messages if you don't include it. This change simply adds a line reminding the new user of the crate to include the `rand_core` feature.
Closes #633

Indicate that the rand_core feature is required

---

curve25519-dalek-derive/Cargo.toml

The popular [`dependency-review-action`](https://github.com/actions/dependency-review-action) requires the license field be in valid SPDX format. (We are hitting false positives on this dependency via `dependency-review-action` over at [Teleport](https://github.com/gravitational/teleport)).

Updates license field to valid SPDX format

---

curve25519-dalek/src/backend/serial/u64/scalar.rs

Timing variability of any kind is problematic when working with potentially secret values such as elliptic curve scalars, and such issues can potentially leak private keys and other secrets. Such a problem was recently discovered in `curve25519-dalek`.
The `Scalar52::sub` function contained usage of a mask value inside of a loop where LLVM saw an opportunity to insert a branch instruction (`jns` on x86) to conditionally bypass this code section when the mask value is set to zero, as can be seen in godbolt:
https://godbolt.org/z/PczYj7Pda
A similar problem was recently discovered in the Kyber reference implementation:
https://groups.google.com/a/list.nist.gov/g/pqc-forum/c/hqbtIGFKIpU/m/cnE3pbueBgAJ
As discussed on that thread, one portable solution, which is also used in this PR, is to …

SECURITY: fix timing variability in backend/serial/u64/scalar.rs

---

curve25519-dalek/src/backend/serial/u32/scalar.rs

Similar security fix to #659, but for the 32-bit backend. See that PR for more information about the problem.

SECURITY: fix timing variability in backend/serial/u32/scalar.rs

---

curve25519-dalek/src/backend/serial/u32/scalar.rs
curve25519-dalek/src/backend/serial/u64/scalar.rs

Alternative to #659/#661 and #662 which leverages `subtle::Choice` and `subtle::ConditionallySelectable` as the optimization barriers.
Really the previous masking was there to conditionally add the scalar field modulus on underflow, so instead of that, we can conditionally select zero or the modulus using a `Choice` constructed from the underflow bit.
TODO: verify codegen and check benchmarks

curve: use `subtle::Choice` for constant-time fixes

---

curve25519-dalek/Cargo.toml
curve25519-dalek/src/backend/vector/ifma/edwards.rs
curve25519-dalek/src/backend/vector/ifma/field.rs
curve25519-dalek/src/lib.rs

The `unexpected_cfgs` lint was previously disabled in 9252fa5c0d09054fed. Since the lint can now be configured using `Cargo.toml`[^2] no `build.rs` shenanigans are necessary anymore.
This PR also fixes some immediate bugs found, two tests used comma-seperated config flags `cfg(target_feature = "avx512ifma,avx512vl")`, which is invalid (and always false). Instead, it should be `cfg(all(target_feature = "avx512ifma", target_feature = "avx512vl"))`.
From what I've seen, this pattern also exists in the proc-macros used to enable target features for certain functions. But I don't understand the codebase well enough to say this for certain, and I didn't look too much into it either.
I believe usage `cfg(nightly)` is also a bug - the documentation[^1] seems to suggest that features are …

Enable unexpected cfgs lint

---

curve25519-dalek/src/edwards.rs
curve25519-dalek/src/ristretto.rs

This PR makes a few small documentation fixes:
- It updates the `ristretto` module documentation to correctly note that `RistrettoPoint` equality testing is always done [in constant time](https://github.com/dalek-cryptography/curve25519-dalek/blob/5b7082bbc8e0b2106ab0d956064f61fa0f393cdc/curve25519-dalek/src/ristretto.rs#L822-L826).
- It updates the `edwards` module documentation to correctly note that `EdwardsPoint` equality testing is always done [in constant time](https://github.com/dalek-cryptography/curve25519-dalek/blob/5b7082bbc8e0b2106ab0d956064f61fa0f393cdc/curve25519-dalek/src/edwards.rs#L495-L499).
- It updates the `EdwardsPoint` documentation to fix what appears to be a copy-paste error for a type name.

docs: minor documentation fixes

---

curve25519-dalek/src/edwards.rs

This PR adds the `Default`, `ConstantTimeEq`, and `ConditionallySelectable` traits to `SubgroupPoint`. Each simply uses the underlying Edwards point functionality.
Closes #580.

edwards: add `SubgroupPoint` traits

---

curve25519-dalek/src/backend/serial/scalar_mul/precomputed_straus.rs
curve25519-dalek/src/backend/vector/scalar_mul/precomputed_straus.rs
curve25519-dalek/src/ristretto.rs
curve25519-dalek/src/traits.rs

It may be useful to support multiscalar multiplication evaluation using partial precomputation, where a larger set of precomputation tables is generated than is needed for an evaluation.
This PR adds such functionality with minimal impact. Specifically, it does so by relaxing the panic conditions on the relevant `VartimePrecomputedMultiscalarMul` functions (and their corresponding implementations). It also adds tests and updates the documentation carefully.
Note that this is an improved version of #546, which was closed due to repository reorganization.

curve: partial precomputation

---

curve25519-dalek/CHANGELOG.md
curve25519-dalek/Cargo.toml
curve25519-dalek/README.md
curve25519-dalek/build.rs
curve25519-dalek/src/backend/mod.rs
curve25519-dalek/src/backend/vector/mod.rs
curve25519-dalek/src/backend/vector/scalar_mul/pippenger.rs
curve25519-dalek/src/backend/vector/scalar_mul/precomputed_straus.rs
curve25519-dalek/src/backend/vector/scalar_mul/straus.rs
curve25519-dalek/src/backend/vector/scalar_mul/variable_base.rs
curve25519-dalek/src/backend/vector/scalar_mul/vartime_double_base.rs

Closes #694 #635 #693
Provides `cfg(curve25519_dalek_backend = "unstable_avx512")`
**Errors**
- If nightly is not in use -> Must use nightly in order to use it (similar to compiler main when attempting to use unstables)
- If not x86_64 simd capable target -> As with simd error out similarly
**Note**: I avoided whole lot of any(curve25519_dalek_backend = "simd", curve25519_dalek_backend = "unstable_avx512") gating because compilre allows multi-value per cfg-key where we emit "simd" in addition to unstable_avx512 when potential use validated giving AVX2 fallback through simd.
If it's desirable to instead have explicit gating then let me know - but it pollutes a lot of gating.

Make AVX512IFMA opt-in backend

---

ed25519-dalek/src/verifying.rs

Removes the previous warning that points are unvalidated: they're validated using the ZIP-215 rules, which allows unreduced y-coordinates. Points are ensured valid by performing decompression, which finds a solution to the curve equation, or returns an error.
Adds references to ZIP-215 and dalek-cryptography/curve25519-dalek#626 which is an issue about potentially adding support for the RFC8032/NIST validation criteria in the future.

ed: update `VerifyingKey::from_bytes` with ZIP-215 info

---

curve25519-dalek/src/backend/vector/avx2/edwards.rs
curve25519-dalek/src/backend/vector/packed_simd.rs
curve25519-dalek/src/edwards.rs
curve25519-dalek/src/montgomery.rs
curve25519-dalek/src/ristretto.rs
ed25519-dalek/src/signing.rs

Clippy 1.81 brings new lints, this fixes those warnings

{curve,ed}25519-dalek: clippy fixes

---

.github/workflows/ed25519-dalek.yml
.github/workflows/workspace.yml
Cargo.toml
curve25519-dalek/src/backend/vector/avx2/edwards.rs
curve25519-dalek/src/backend/vector/packed_simd.rs
curve25519-dalek/src/edwards.rs
curve25519-dalek/src/montgomery.rs
curve25519-dalek/src/ristretto.rs
ed25519-dalek/Cargo.toml
ed25519-dalek/src/signing.rs

ed25519-dalek: fixup pkcs8 API break

---

ed25519-dalek/README.md

- Remove extra ' in definition of malleability
The README states:
> A signature scheme is considered to produce _malleable signatures_ if a passive attacker with knowledge of a public key _A_, message _m_, and valid signature _σ'_ can produce a distinct _σ'_ such that _σ'_ is a valid signature of _m_ with respect to _A_.
Haven't had my morning coffee but I think the first `σ` in `valid signature _σ'_ can produce a distinct _σ'_ ` should be just `σ` (without the `'`).

Update README.md Malleability definition

---

curve25519-dalek/src/backend/mod.rs
curve25519-dalek/src/backend/serial/scalar_mul/precomputed_straus.rs
curve25519-dalek/src/backend/vector/scalar_mul/precomputed_straus.rs
curve25519-dalek/src/edwards.rs
curve25519-dalek/src/ristretto.rs
curve25519-dalek/src/traits.rs

Adds functionality to `VartimePrecomputedMultiscalarMul` to return the number of points in the precomputation.

curve: add precomputation length

---

curve25519-dalek/src/ristretto.rs

It is the case that performing variable-time Ristretto multiscalar multiplication evaluation using [`VartimeRistrettoPrecomputation`](https://docs.rs/curve25519-dalek/latest/curve25519_dalek/ristretto/struct.VartimeRistrettoPrecomputation.html) may be less efficient than the corresponding [`VartimeMultiscalarMul`](https://docs.rs/curve25519-dalek/latest/curve25519_dalek/traits/trait.VartimeMultiscalarMul.html) implementation, depending on the number of points used.
This PR updates the documentation to make this clear, since the decision of whether or not to use precomputation may depend highly on the use case.

docs: update `VartimeRistrettoPrecomputation` documentation

---

curve25519-dalek/src/edwards.rs

This PR adds `Zeroizing` support to `SubgroupPoint`, as it was missing.
Closes #617.

curve: support zeroizing for `SubgroupPoint`

---

x25519-dalek/src/x25519.rs

This PR replaces all uses of the deprecated `#[zeroize(drop)]` attribute with `ZeroizeOnDrop`.
Closes #719.

x25519: use `ZeroizeOnDrop` exclusively

---

curve25519-dalek/Cargo.toml

This fixes warnings like:
```
warning: unexpected `cfg` condition value: ``
--> curve25519-dalek/src/backend/mod.rs:58:9
|
58 |         cpufeatures::new!(cpuid_avx512, "avx512ifma", "avx512vl");
|         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

chore(deps): bump `cpufeatures` from `0.2.12` to `0.2.17`

---

curve25519-dalek/src/lib.rs

The build is currently broken because it's been stabilized:
error: the feature `avx512_target_feature` has been stable since 1.89.0-nightly and no longer requires an attribute to enable

curve: remove `feature(avx512_target_feature)`

---

curve25519-dalek-derive/tests/tests.rs

The test assumed that the 'avx2' target_feature would never be set and used this fact to verify that unsafe_target_feature would correctly not even compile test functions maked with that target_feature. As of CentOS 10 and derivatives, the avx2 target_feature is now set by the system rustc, so let's use a target_feature less likely to appear in the real world.
Closes #755

Fix curve25519-dalek-derive test compilation on CentOS 10 x86_64

---

ed25519-dalek/CHANGELOG.md
ed25519-dalek/src/hazmat.rs
ed25519-dalek/src/signing.rs
ed25519-dalek/src/verifying.rs
ed25519-dalek/src/verifying/stream.rs
ed25519-dalek/tests/ed25519.rs

see description and discussion in https://github.com/dalek-cryptography/curve25519-dalek/pull/556
this PR reuses all commits from that one, and adds in the feature guard we talked about
~nightly CI failure is unrelated~

Sign/verify by digest update + StreamVerifier

---

ed25519-dalek/src/hazmat.rs
ed25519-dalek/src/signing.rs

Currently, if you want to sign a serialized object, you have to serialize it in full, then sign it. When memory is constrained, this is hard.
This PR defines a function, `hazmat::raw_sign_byupdate`, which, rather than taking a single contiguous message slice, takes a `Fn(&mut Digest)` that knows how to update a hasher with the parts of the message. So, in the case of serialization, the closure will simply serialize each component to a small buffer, do `h.update(buf)`, then fill the buffer with the next serialized component, etc.
This comes from discussion [here](https://github.com/dalek-cryptography/curve25519-dalek/pull/735#discussion_r2119269994), [here](https://github.com/dalek-cryptography/curve25519-dalek/pull/556#issuecomment-1707656494), and hypothetical impl …

ed: Expose `hazmat::raw_sign_byupdate()` for streamed signing

---

curve25519-dalek-derive/src/lib.rs
curve25519-dalek/src/backend/serial/fiat_u32/field.rs
curve25519-dalek/src/backend/serial/fiat_u64/field.rs
curve25519-dalek/src/backend/serial/u32/field.rs
curve25519-dalek/src/backend/serial/u32/scalar.rs
curve25519-dalek/src/backend/serial/u64/field.rs
curve25519-dalek/src/backend/serial/u64/scalar.rs
curve25519-dalek/src/edwards.rs
curve25519-dalek/src/field.rs
curve25519-dalek/src/montgomery.rs
curve25519-dalek/src/ristretto.rs
curve25519-dalek/src/scalar.rs

Methods named `as_*` should perform a zero-cost  borrowing conversion:
https://rust-lang.github.io/api-guidelines/naming.html#ad-hoc-conversions-follow-as_-to_-into_-conventions-c-conv
Methods named `to_*` can perform an expensive owned conversion.
Since the `FieldElement*` types are technically part of the public API (but feature gated), this also preserves the old names with a deprecation. We can remove them in the next breaking release.
The same change was also made to the backend `Scalar*` types, however these types are not a part of the public API.

curve: rename `FieldElement*::as_bytes` => `::to_bytes`

---

ed25519-dalek/Cargo.toml

I tried to compile `ed25519-dalek` using the new https://github.com/Rust-GPU/Rust-CUDA reboot and they mentioned they fixed a lot of issue, and I tried to include curve25519-dalek and it does miraculously compile, except it has to be without `zeroize` which is complaining about atomic fence not supported on PTX, and I have to use the equivalent intrinsic in cuda_std instead. 
As a quick demo for an internal finite field arithmetic + SIMD project and I rather need performance, I don't need zeroize at all. So a quick solution is to just disable it.
Anyway, I noticed with ed25519-dalek, when you enable the alloc feature, zeroize is implicitly enabled. This PR just add a single character to fix that

Don't implicitly enable zeroize for ed25519-dalek alloc feature

---

ed25519-dalek/src/signing.rs
ed25519-dalek/src/verifying.rs

This allows to use ed25519 to create certificates for example
Related to #707 & https://github.com/RustCrypto/signatures/pull/889
This partially reverts #712
This is a revive of https://github.com/dalek-cryptography/curve25519-dalek/pull/728 after target branch got removed.

ed25519-dalek: use `SignatureAlgorithmIdenfier` instead of the dynamic counterpart

---

curve25519-dalek/src/backend/serial/fiat_u32/field.rs
curve25519-dalek/src/backend/serial/fiat_u64/field.rs
curve25519-dalek/src/backend/serial/u32/field.rs
curve25519-dalek/src/backend/serial/u64/field.rs
curve25519-dalek/src/backend/vector/avx2/edwards.rs
curve25519-dalek/src/constants.rs
curve25519-dalek/src/edwards.rs
curve25519-dalek/src/scalar.rs
x25519-dalek/src/x25519.rs
x25519-dalek/tests/x25519_tests.rs

One thing that isn't clear is how to deprecated `Scalar::from_bits`. Ed uses this public function in `legacy_compatability` mode. We can't remove it because it's a direct dependency. And we can't vendor it in Ed because Ed doesn't have access to the type's fields. Should this just be a perma-visible deprecation?

curve,x: Clear deprecated functions

---

curve25519-dalek/src/edwards.rs

This ensures that `CompressedEdwardsY` equality testing is always done in constant time.
BREAKING CHANGE: This can [break](https://github.com/dalek-cryptography/curve25519-dalek/pull/669#discussion_r1667195282) certain uses of `match`.

curve!: use constant-time compressed Edwards equality testing

---

curve25519-dalek/src/edwards.rs

The `CofactorGroup` documentation for `EdwardsPoint` merely notes that Ristretto has a trivial cofactor. This is true, but seems out of place here, and seems like it could confuse the reader into thinking this holds for `EdwardsPoint` as well (which it most certainly [does not](https://github.com/dalek-cryptography/curve25519-dalek/blob/0964f800ab2114a862543ca000291a6e3531c203/curve25519-dalek/src/edwards.rs#L1186-L1189)).

docs: remove unnecessary `CofactorGroup` documentation

---

curve25519-dalek/CHANGELOG.md
curve25519-dalek/Cargo.toml
ed25519-dalek/CHANGELOG.md
ed25519-dalek/Cargo.toml

I updated the changelogs and version numbers for our stable branch. I think this is the last thing to do for cutting minor releases for curve and ed.

Stable: Update changelogs and bump minor version numbers

---

x25519-dalek/CHANGELOG.md
x25519-dalek/src/x25519.rs

As discussed somewhat in https://github.com/dalek-cryptography/curve25519-dalek/pull/747, we should not implement `Zeroize` for types that can be badly misused when zeroed (ie secrets), and we do not need to implement `ZeroizeOnDrop` for types that don't need to always be zeroized (ie not-necessarily-secrets).
This basically means every type should at most implement `Zeroize` XOR `ZeroizeOnDrop`.
Previously, some of the x25519 secret types implemented both. Since they're secrets, we keep `ZeroizeOnDrop` and remove `Zeroize`.

x: Remove Zeroize impl for secret types

---

ed25519-dalek/Cargo.toml

This also relax the dependency to use future RC versions of signature

chore(deps): bump `signature` to `3.0.0-rc.2`

---

curve25519-dalek/benches/dalek_benchmarks.rs
curve25519-dalek/src/backend/serial/u32/constants.rs
curve25519-dalek/src/backend/serial/u64/constants.rs
curve25519-dalek/src/edwards.rs
curve25519-dalek/src/field.rs
curve25519-dalek/src/montgomery.rs

Sorry for the misunderstanding - it was a long time I did the original PR 🙏  Here is a PR with the proper hash_to_curve implementation. 
When implementing, I did a stupid mistake that got me debugging for a couple of hours, and just to make sure that the issue was not the elligator (which it was not) I implemented the inline description of the draft. I found the function `pow_p58`, which is the one I thought was missing originally. Let me know if you prefer this inline version or the one we had before. Both work (turned out that the mistake was me hardcoding incorrect test vectors 🥲 )
The other important mention is that I've used `unsafe` code to be able to not use `alloc` in `hash_to_field`. I was trying several ways, but couldn't get anything better. I'm sure you've found similar issues …

Add proper hash_to_curve. 

---

curve25519-dalek/CHANGELOG.md
curve25519-dalek/benches/dalek_benchmarks.rs
curve25519-dalek/src/scalar.rs

Current `Scalar::batch_invert()` allocates some scratch space as a `Vec`. This PR adds a method to do batch inversion without allocation and not requiring `alloc`.
To that effect I renamed `Scalar::batch_invert()` to `Scalar::batch_alloc_invert()`. The new method, taking the old ones name, `Scalar::batch_invert()` now takes a `const N` specifying the size for the scratch space and its argument `&mut [Scalar; N]`.

Add fixed-array `Scalar` batch inversion

---

curve25519-dalek/Cargo.toml
ed25519-dalek/Cargo.toml

Updates the following dependencies (which now use `hybrid-array` v0.4 instead of v0.3):
- `blake2` v0.11.0-rc.2
- `digest` v0.11.0-rc.1
- `ed25519` v3.0.0-rc.0
- `sha2` v0.11.0-rc.2
- `sha3` v0.11.0-rc.2
- `signature` v3.0.0-rc.3

Bump RustCrypto dependencies
