src/curve.rs

This allows other compression formats (e.g., CompressedMontgomeryX).

Rename CompressedPoint -> CompressedEdwardsY

---

src/curve.rs

Link is broken here https://docs.rs/curve25519-dalek/0.1.3/curve25519_dalek/curve/index.html

Link needs http://www.

---

src/curve.rs

Cut out boilerplate using a derive directive.

Derive Eq, PartialEq for CompressedEdwardsY

---

src/curve.rs

A few commits on top of hdevalence's PR #32 to cleanup the decompression and match Signal's behaviour.

Montgomery-U format, revised

---

src/constants.rs
src/curve.rs
src/field.rs
src/scalar.rs

Various fixes to deal with issues flagged by rust-clippy.

Clippy fixes

---

Cargo.toml

These are the latest releases of these crates.

Update digest => 0.7, generic_array => 0.9

---

Cargo.toml
src/backend/avx2/edwards.rs
src/backend/avx2/field.rs
src/backend/u32/field.rs
src/backend/u64/field.rs
src/constants.rs
src/curve_models/mod.rs
src/curve_models/window.rs
src/edwards.rs
src/field.rs
src/montgomery.rs
src/ristretto.rs
src/scalar.rs
src/traits.rs

This PR has two commits: one which updates to use the new `subtle` API, and another that patches the `Cargo.toml` to pull the `subtle` develop branch. Before this is merged, but after the `subtle` changes are released, that should be replaced with just a dep version bump.

Update to new `subtle` API (WIP)

---

src/montgomery.rs

This small change results in less changes to the x25519-dalek code to upgrade to the latest version.

Define mul variants for MontgomeryPoints.

---

LICENSE
README.md
src/backend/avx2/constants.rs
src/backend/avx2/edwards.rs
src/backend/avx2/field.rs
src/backend/avx2/mod.rs
src/backend/mod.rs
src/backend/u32/constants.rs
src/backend/u32/field.rs
src/backend/u32/mod.rs
src/backend/u64/constants.rs
src/backend/u64/field.rs
src/backend/u64/mod.rs
src/constants.rs
src/curve_models/mod.rs
src/edwards.rs
src/field.rs
src/lib.rs
src/macros.rs
src/montgomery.rs
src/ristretto.rs
src/scalar.rs
src/scalar_mul/window.rs
src/traits.rs

This fixes some issues in #148

some pre-1.0.0 cleanup

---

src/lib.rs
src/scalar.rs

More various doctests and cleanups for #148.

Feature/148 cleanup for 1.0.0 pre.0 1

---

src/curve_models/mod.rs
src/edwards.rs
src/montgomery.rs
src/ristretto.rs

impl Default for remaining point types

---

.travis.yml
Cargo.toml
build.rs
src/backend/avx2/scalar_mul/straus.rs
src/backend/mod.rs
src/edwards.rs
src/field.rs
src/lib.rs
src/montgomery.rs
src/prelude.rs
src/ristretto.rs
src/scalar.rs
src/scalar_mul/straus.rs

Reverts dalek-cryptography/curve25519-dalek#170

Revert "Unify `alloc` and `std` cargo features"

---

.travis.yml
Cargo.toml
build.rs
src/backend/avx2/scalar_mul/straus.rs
src/backend/mod.rs
src/edwards.rs
src/field.rs
src/lib.rs
src/montgomery.rs
src/prelude.rs
src/ristretto.rs
src/scalar.rs
src/scalar_mul/straus.rs

Unify `alloc` and `std` cargo features (rebased #170)

---

Cargo.toml
build.rs
src/backend/avx2/constants.rs
src/backend/avx2/field.rs
src/lib.rs

Migrate to packed_simd from core::simd

---

README.md

Add note on FFI to README.md

---

Cargo.toml
src/backend/avx2/edwards.rs
src/backend/avx2/field.rs
src/backend/u32/field.rs
src/backend/u64/field.rs
src/curve_models/mod.rs
src/edwards.rs
src/field.rs
src/montgomery.rs
src/ristretto.rs
src/scalar.rs
src/scalar_mul/window.rs

This allows the autoimplementation of the other subtle traits
Closes #200

Change to subtle::ConditionallySelectable

---

Cargo.toml

Update to use Rand 0.6

---

src/backend/serial/scalar_mul/variable_base.rs

This saves 4 point doublings by unwrapping the first loop iteration,
as well as 63 field multiplications (one per iteration) by managing
curve model choice explicitly.
Benchmark (the absolute numbers are slow, because it's on a turbo-disabled laptop, but the relative change is consistent):
```text
Constant-time variable-base scalar mul                        
time:   [98.208 us 98.334 us 98.473 us]
change: [-2.8943% -2.4276% -1.9647%] (p = 0.00 < 0.05)
Performance has improved.
Found 9 outliers among 100 measurements (9.00%)
2 (2.00%) high mild
7 (7.00%) high severe
```

 Save 2.5% on variable-base scmul by squeezing some multiplications. 

---

src/traits.rs

Non-functional change. Allow non-snake case in whole file to suppress warning in the following line.
https://github.com/dalek-cryptography/curve25519-dalek/blob/f630041af28e9a405255f98a8a93adca18e4315b/src/traits.rs#L328

Quench snake case warning

---

src/scalar.rs

Found by @3for; this only affected width-7 NAF computations, which were never
used in the source tree (only width 5, optimal for dynamic cases, and 8, better
for static cases).
Closes #272

Add a missing wrapping_sub in NAF computation.

---

README.md

README.md parallel_doc link fix

---

src/montgomery.rs
src/ristretto.rs
src/scalar.rs

This branch merge-rebases @DebugSteven's PR #236 on top of @tarcieri's already-merged #294 work.

Implement Zeroize for Scalar and MontgomeryPoint

---

src/edwards.rs
src/montgomery.rs
src/ristretto.rs
src/scalar.rs

Hello!
I need CompressedRistretto to implement Hash for a project. Can you add it, please?
Thanks!

Derive of Hash trait to CompressedRistretto

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md

This helps Github's UI show that we have one and autolink to it.

Move CoC section from CONTRIBUTING.md to new file.

---

Cargo.toml

bumped packed_simd to 0.3.4

---

README.md

Includes both version and download count

README.md: use buildstats.info crate badge

---

CHANGELOG.md
Cargo.toml
README.md

- ed25519 rc.3: https://github.com/dalek-cryptography/ed25519-dalek/pull/307
- x25519 rc.3: https://github.com/dalek-cryptography/x25519-dalek/pull/128

chore: Release 4.0.0-rc.3

---

curve25519-dalek-derive/Cargo.toml

Bump `quote` and `syn`

---

curve25519-dalek/Cargo.toml
curve25519-dalek/README.md
ed25519-dalek/Cargo.toml
x25519-dalek/Cargo.toml

curve: Bump version to 4.0.0

---

curve25519-dalek/CHANGELOG.md
curve25519-dalek/Cargo.toml
curve25519-dalek/README.md

4.1.0 Adds:
- #555 
- #562 
- #566 
4.1.0 Fixes:
- #558 
- #568 
- #572 
Pending:
- https://github.com/dalek-cryptography/curve25519-dalek/pull/575

curve: Release 4.1.0

---

curve25519-dalek/CHANGELOG.md
curve25519-dalek/docs/ifma-notes.md
ed25519-dalek/tests/validation_criteria.rs

Found few minor typos and fixed them. That's about it. Have a nice day.

chore: typo fix

---

ed25519-dalek/README.md

Corrected path to CONTRIBUTING.md
Current link leads to File Not Found

Updating dead link in  ed25519-dalek/README.md

---

curve25519-dalek/src/backend/mod.rs
curve25519-dalek/src/backend/serial/curve_models/mod.rs
curve25519-dalek/src/backend/serial/fiat_u32/field.rs
curve25519-dalek/src/backend/serial/fiat_u64/field.rs
curve25519-dalek/src/backend/serial/u32/field.rs
curve25519-dalek/src/backend/serial/u32/scalar.rs
curve25519-dalek/src/backend/serial/u64/field.rs
curve25519-dalek/src/backend/serial/u64/scalar.rs
curve25519-dalek/src/edwards.rs
curve25519-dalek/src/ristretto.rs
curve25519-dalek/src/scalar.rs
curve25519-dalek/src/window.rs
ed25519-dalek/src/signature.rs
ed25519-dalek/src/signing.rs
ed25519-dalek/src/verifying.rs

Was adding wycheproofs but saw nightly clippy added a lint for unnecessary qualifications so here's sweep :)
https://github.com/pinkforest/curve25519-dalek/actions/runs/8194487390/job/22410632921#step:4:735

Address new nightly clippy unnecessary qualifications

---

ed25519-dalek/src/signing.rs

an -> a in ed25519-dalek/src/signing.rs

chore: fix a typo
